make-examples:
	cd DetectDNSs && $(MAKE)
	cd DetectNetworkARP && $(MAKE)
	cd DetectNetworkICMP && $(MAKE)
	cd DetectNetworkUDP && $(MAKE)
	cd DetectPortsTCP && $(MAKE)
	cd DetectPortsUDP && $(MAKE)
	cd DHCPRelease && $(MAKE)
	cd DNSSpoof && $(MAKE)
	cd NetworkAnalyse && $(MAKE)
	cd NetworkJammer && $(MAKE)
	cd NetworkMonitor && $(MAKE)
	cd NetworkMonitorDNS && $(MAKE)
	cd NetworkMonitorCookies && $(MAKE)
	cd NetworkMonitorWebsites && $(MAKE)
	cd NetworkReadPCAP && $(MAKE)
	cd NetworkStoreDB && $(MAKE)
	cd NetworkStorePCAP && $(MAKE)
	cd OutgoingConnections && $(MAKE)
	cd Traceroute && $(MAKE)
	cd VictimIsUp && $(MAKE)
	cd VictimsMonitor && $(MAKE)
	cd VictimSmurfAttack && $(MAKE)

clean-examples:
	find ./ -name "*.o" -type f -delete
	find ./ -name "*.out" -type f -delete
