language: generic
os:
- linux
addons:
   apt:
       sources:
        - ubuntu-toolchain-r-test
       packages:
        - cmake-data
        - cmake
        - g++-6
env:
  - COMPILER_NAME=gcc CXX=g++-6 CC=gcc-6

sudo: required
before_install:
    - sudo apt-get install libpcap-dev

install:
    - export CXX="g++-6" CC="gcc-6"

script:
    - mkdir build
    - cd build
    - cmake .. && make
    - sudo make install
    - cd ../example
    - mkdir builds
    - cd builds
    - cmake .. && make
