language: cpp
compiler: 
- g++
os:
- linux
addons:
   apt:
       sources:
        - ubuntu-toolchain-r-test
       packages:
        - cmake-data
        - cmake
        - g++-6
env:
  - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

script:
    - mkdir build
    - cd build
    - cmake .. && make
