language: generic
os:
- linux
addons:
   apt:
       sources:
        - ubuntu-toolchain-r-test
       packages:
        - cmake-data
        - cmake
        - g++-6
env:
  - COMPILER_NAME=gcc CXX=g++-6 CC=gcc-6

sudo: required
before_install:
    - sudo apt-get install libpcap-dev
    - sudo apt-get install libgtest-dev
    - cd /usr/src/gtest
    - sudo cmake CMakeLists.txt
    - sudo make 
    - sudo cp *.a /usr/lib
    - pip install --user cpp-coveralls

install:
    - export CXX="g++-6" CC="gcc-6"

script:
    - cd ${TRAVIS_BUILD_DIR}
    - mkdir build
    - cd build
    - cmake .. -DGTEST_FOUND=ON
    - make
    - sudo make install
    - cd ../example
    - mkdir builds
    - cd builds
    - cmake .. && make
    - cd ../../tests
    - mkdir builds
    - cd builds
    - cmake .. && make
    - ./runTests
    - cd ../../build

after_success:
    - lcov --directory . --capture --output-file coverage.info
    - lcov --remove coverage.info '/usr/*' --output-file coverage.info
    - lcov --list coverage.info
    - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
